{% set name = "django-guardian" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-guardian-{{ version }}.tar.gz
  sha256: ed2de26e4defb800919c5749fb1bbe370d72829fbd72895b6cf4f7f1a7607e1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - django >=2.2
    - python >=3.5

test:
  imports:
    - guardian
    - guardian.conf
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django-guardian/django-guardian
  summary: Implementation of per object permissions for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abraha2d
