travis:
  secure:
    BINSTAR_TOKEN: kH5K8yI/qk1o3Jp8lNSdSqlqtJZ8co+KMfnlXR9PHgItl0zEhVm/QFGym5uHYBPIggBpc6HsJi73KC62RmRR5P1/eyhTBunX5jpquduG+jB2aw1uQGT0JO0jRvHbh5nUXeM0LPIujQFYmpZIAWAFnT7D8sel6pOiNFcOVSMdGm9x47cEuGNO9MKm6k0ntP8NxgAJTYvgvwIHrsue0QlW2ZNOaea3Ao8+ZZs3PGqAxHkI9smcb9lkBwYWbsitWrt1BNsEchP/7FhWHxU1TBbFHJ9ILy5YIJPHuvOHB1y3EU7PJQboksXZ8l4rXMaZ1qb785fgTJ1RDqyXBSSIuK1lo8UovlH9Cy2des30gK8AqXII3SJi5+7e8RZhA4vJNFTB2STL0yxLkq47qspnWTOAKQ9CU+e/anlRhthvOf0Iu75VQ8ipf32Dbty6SwsYL0CaYzfO0SAeQs0dN+YLMqdWrEmT7XensoClPoaDPgEJSd/0g6iVUUJDB9lB3pwm7jncVM6gaw8w4hpL1LWLP50g35NDuXfCLHKO6sf1woyGzQzAOc8wL03xiZUPU7Dq8RJYJPCZb6kLZX4MUWDI/5aY/1XOo3Z3pO6HUe6Wx+grS8tN2z+5eQQDdUDMw2XsEZCUAwsC1y9obgxX69GeqTKeLfOcKAO5rXlkCLI+tqQlkdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
