travis:
  secure:
    BINSTAR_TOKEN: yJbYx+ZhderlJ+q08td+W9g4yt609CdtAifegzwGJ821vPtf3ElrWGfz378yzialxW2YMtt6kh4+USFmrK4N1Yi/0Z1/R7RtAKULVIT8J7AXbePHvdGQc7iyN8p1sst1/vX9pddHGdVh+3dpDdX/rBysiVCeszwp6bLpiIqbBTR4G8iywGgmpl7sn164XIwgw3wtBpDm5Mv3CaJaR6XHEX5fmJnq+RXzjPpjCy6+u+IQXzhuddxgoUfNQqvaJZqyMc4Je+WLYyY1uPl7ERRo2FhTu+wuChsx4eOdTwCKwVub7QRSYYLy+smrWTp3wEscj1I7ukZ0vHlONXeLQEQKr5f9LamzzwjMdTCeiixMwtmz5Abrc9Y/29KZJigZ2B/WrWU9fP8sKvH34IWoMi1OUWoH1/3lYrcSHwIcKLvPqN8cOykgtdBjcvi+RDu8/P3nm6WhbFOfjgb8sbJ7wpaNqjLWKgOCMY/kWBcLR6uslrDjJFCkWgoMjRia1CNL78ceyhubCzWZQSv8aJt7ex3JOxL8G2TYTSj+e7J8c2ULlFotQybbB9zIf/g9AOnZOjcWZJ0cS1WrhCD4O5EWERrFqSBnDWAIrWx2FBzdsxGQR1trpdiet27IyAIBqAHcj1j3alOnDaxTAZEA9RoP61SWVVz5qIsOp4cVON+gn41eXyM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
