travis:
  secure:
    BINSTAR_TOKEN: WoLAeyRjwqjKhGtne3SLFb99+0ZPyshjXMET9KQ3nWeuKCX37QmiLUtvUB7/WzN0YUYlJwTvs2uH+GVjQTHxFhqxofIxF110FmK6Wdfoa0+j+aCjWs6MymEIUS3ZqlEuCotSD0yEu9f7zLRw4lhMPqKe8GOTtsyxKwmYb07Z6wTaRyoN8srl9SXjt0vz+L7R5r2xhlifRyxHlw7tub9KDiLEa6vs/0abNQ5kx2tlrogluDUXjNIs4aMqH6XGghaj1F6Dd039D2ae+MIO6/ajSMuCiO4kBGDS2sbxu3NCqpalaePNJBZ4Nj5BYLi4kw+DOt3CMWk9BkmKeGaOG1w4GMH2Cn8HJY+q5oROPPpfQUmcFk1C9Uj46a4BjlgOnqJGiBL0AcsarDIK7p50huIZ1e5fLxzUG6jqlyV2NkBO4bzl3vOvUwkgcT8Z7T9aq/dAAKnejbldX0AOVJ3syEZK4Q1nnDb4FOHb3iBiyJ8umNrkvZMEIzuZnDOvJeTrlZ+BgC4THIIxuPbV5I7fAx1uytYDjVrTJ8So2VZZ07wwciaXynETZUZdUNQgveanfsxsfUXrlJwm7SzUId0IAEd3MQkRdSeWYr10Ph7YlVx6Xp7BT9I3HlbRrzIIa8pOIrv7DwMhVr2lqfq3WvAFUrz99QH8OPIX1LKOVX5+ROBb2eo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
